from iterator import *
primos = [1,2,3,5,7,9,11]
iterator=iterator(primos)
print(iterator.iterar())
print(iterator.iterar())
print(iterator.iterar())
print(iterator.iterar())
print(iterator.iterar())
print(iterator.iterar())
print(iterator.iterar())
print(iterator.reversa())
print(iterator.reversa())
print(iterator.reversa())
print(iterator.reversa())
print(iterator.reversa())
print(iterator.reversa())
print(iterator.reversa())
print(iterator.reversa())
print(iterator.reversa())
